#!/bin/bash
while true; do

echo " s - wykonuje polecenie ls -s"
echo " l - wykonuje polecenie ls -l"
echo " c - wykonuje polecenie ls *.c"
echo " koniec - wyjscie"
read -p "Wybierz opcje: " opcja

case $opcja in
s)
        ls -s
        ;;
l)
        ls -l
        ;;
c)
        ls *.c
        ;;
koniec)
        exit 0
        ;;
*)
        echo "zly wybor"
        ;;
esac
done

